/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6c2feb0b-3edd-4ea3-be81-a5878ac99920",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hz5RfRulH",
    "aws_user_pools_web_client_id": "20mqm0mv897opqoun5oborj2r1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://enmu77vr65hrbou5n7srxutr6y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456"
};


export default awsmobile;
